#!/bin/sh
set -eu
if [ ! -x bot ] || [ bot.cpp -nt bot ] || [ ../../templates/cpp/runner.cpp -nt bot ] || [ ../../templates/cpp/strategy.cpp -nt bot ] || [ ../../templates/cpp/strategy.hpp -nt bot ]; then
    ./build
fi
exec ./bot
